apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-traffic
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: tyk-assignment-go
      app.kubernetes.io/name: tyk-assignment-go
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
